2021-03-15 12:18:01,178 INFO    MainThread:9227 [wandb_setup.py:_flush():69] setting env: {}
2021-03-15 12:18:01,178 INFO    MainThread:9227 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-15 12:18:01,178 INFO    MainThread:9227 [wandb_init.py:_log_setup():334] Logging user logs to /cbr/saish/PhD/DL/Assignment_1/wandb/run-20210315_121801-3oqfu36p/logs/debug.log
2021-03-15 12:18:01,179 INFO    MainThread:9227 [wandb_init.py:_log_setup():335] Logging internal logs to /cbr/saish/PhD/DL/Assignment_1/wandb/run-20210315_121801-3oqfu36p/logs/debug-internal.log
2021-03-15 12:18:01,179 INFO    MainThread:9227 [wandb_init.py:init():367] calling init triggers
2021-03-15 12:18:01,179 INFO    MainThread:9227 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'batch_size': 64, 'l_rate': 0.001, 'optimizer': 'mgd', 'epochs': 5, 'activation': 'tanh', 'initializer': 'xavier', 'loss': 'cross_entropy'}
2021-03-15 12:18:01,179 INFO    MainThread:9227 [wandb_init.py:init():416] starting backend
2021-03-15 12:18:01,179 INFO    MainThread:9227 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-03-15 12:18:01,188 INFO    MainThread:9227 [backend.py:ensure_launched():123] starting backend process...
2021-03-15 12:18:01,192 INFO    MainThread:9227 [backend.py:ensure_launched():128] started backend process with pid: 9302
2021-03-15 12:18:01,193 INFO    MainThread:9227 [wandb_init.py:init():421] backend started and connected
2021-03-15 12:18:01,194 INFO    MainThread:9227 [wandb_init.py:init():461] updated telemetry
2021-03-15 12:18:01,194 INFO    MainThread:9227 [wandb_init.py:init():480] communicating current version
2021-03-15 12:18:02,189 INFO    MainThread:9227 [wandb_init.py:init():485] got version response 
2021-03-15 12:18:02,189 INFO    MainThread:9227 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-15 12:18:02,481 INFO    MainThread:9227 [wandb_init.py:init():518] starting run threads in backend
2021-03-15 12:18:03,782 INFO    MainThread:9227 [wandb_run.py:_console_start():1480] atexit reg
2021-03-15 12:18:03,782 INFO    MainThread:9227 [wandb_run.py:_redirect():1343] redirect: SettingsConsole.REDIRECT
2021-03-15 12:18:03,783 INFO    MainThread:9227 [wandb_run.py:_redirect():1348] Redirecting console.
2021-03-15 12:18:03,783 INFO    MainThread:9227 [redirect.py:install():213] install start
2021-03-15 12:18:03,783 INFO    MainThread:9227 [redirect.py:install():228] install stop
2021-03-15 12:18:03,783 INFO    MainThread:9227 [redirect.py:install():213] install start
2021-03-15 12:18:03,783 INFO    MainThread:9227 [redirect.py:install():228] install stop
2021-03-15 12:18:03,783 INFO    MainThread:9227 [wandb_run.py:_redirect():1394] Redirects installed.
2021-03-15 12:18:03,783 INFO    MainThread:9227 [wandb_init.py:init():542] run started, returning control to user process
2021-03-15 12:38:59,637 ERROR   stdout    :9227 [redirect.py:_pipe_relay():139] problem in pipe relay
Traceback (most recent call last):
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 137, in _pipe_relay
    cb(name, data)
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 796, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 187, in publish_output
    self._publish_output(o)
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 192, in _publish_output
    self._publish(rec)
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 518, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2021-03-15 12:39:01,358 ERROR   stderr    :9227 [redirect.py:_pipe_relay():139] problem in pipe relay
Traceback (most recent call last):
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 137, in _pipe_relay
    cb(name, data)
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 796, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 187, in publish_output
    self._publish_output(o)
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 192, in _publish_output
    self._publish(rec)
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 518, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2021-03-15 12:39:01,367 INFO    MainThread:9227 [wandb_run.py:_atexit_cleanup():1450] got exitcode: 1
2021-03-15 12:39:01,367 INFO    MainThread:9227 [wandb_run.py:_restore():1422] restore
2021-03-15 12:39:01,367 INFO    MainThread:9227 [redirect.py:uninstall():232] uninstall start
2021-03-15 12:39:01,368 INFO    MainThread:9227 [redirect.py:_stop():287] _stop: stdout
2021-03-15 12:39:01,372 INFO    stdout    :9227 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2021-03-15 12:39:01,372 INFO    stdout    :9227 [redirect.py:_pipe_relay():145] relay done done: stdout
2021-03-15 12:39:01,372 INFO    MainThread:9227 [redirect.py:_stop():293] _stop closed: stdout
2021-03-15 12:39:01,372 INFO    MainThread:9227 [redirect.py:_stop():299] _stop joined: stdout
2021-03-15 12:39:01,372 INFO    MainThread:9227 [redirect.py:_stop():301] _stop rd closed: stdout
2021-03-15 12:39:01,373 INFO    MainThread:9227 [redirect.py:uninstall():236] uninstall done
2021-03-15 12:39:01,373 INFO    MainThread:9227 [redirect.py:uninstall():232] uninstall start
2021-03-15 12:39:01,373 INFO    MainThread:9227 [redirect.py:_stop():287] _stop: stderr
2021-03-15 12:39:01,373 INFO    MainThread:9227 [redirect.py:_stop():293] _stop closed: stderr
2021-03-15 12:39:01,373 INFO    stderr    :9227 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2021-03-15 12:39:01,373 INFO    stderr    :9227 [redirect.py:_pipe_relay():145] relay done done: stderr
2021-03-15 12:39:01,373 INFO    MainThread:9227 [redirect.py:_stop():299] _stop joined: stderr
2021-03-15 12:39:01,373 INFO    MainThread:9227 [redirect.py:_stop():301] _stop rd closed: stderr
2021-03-15 12:39:01,373 INFO    MainThread:9227 [redirect.py:uninstall():236] uninstall done
2021-03-15 12:39:01,374 INFO    MainThread:9227 [wandb_run.py:_restore():1422] restore
2021-03-15 12:39:06,860 ERROR   MainThread:9227 [wandb_run.py:_atexit_cleanup():1468] Problem finishing run
Traceback (most recent call last):
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1458, in _atexit_cleanup
    self._on_finish()
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1615, in _on_finish
    self._backend.interface.publish_telemetry(self._telemetry_obj)
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 226, in publish_telemetry
    self._publish(rec)
  File "/cbr/saish/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 518, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
